### PR TITLE
Update ClanMemberListSortPlugin.java

### PR DESCRIPTION
**Pull request by Nick2bad4u**
Tried to fix the flickering on rank updates that displays the default sort, then changes back to the plugin custom sort

### CODE REVIEW

**Comment by erwinvc** [comment]
Awesome, thanks! I'll make sure to test it and I'll open a pull request for the plugin soon.

**Comment by Nick2bad4u** [comment]
> Awesome, thanks! I'll make sure to test it and I'll open a pull request for the plugin soon.

Were you able to test it? Wondering if it works on your end

Edit: its live in game now and appears to be working... so far

**Comment by erwinvc** [comment]
Yeah seems to be working as intended, thanks again.

**Comment by Nick2bad4u** [comment]
> Yeah seems to be working as intended, thanks again.

I still notice it flashes if you manually refresh, but besides that it seems ok.

**Pull request merged**
